# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Zthxxx's Blog
subtitle: Life is short, you need python.
description: 面向 Google 和 StackOverflow 编程的 蒟蒻 coder，各方面都是辣鸡，但是觉得好玩就不会放弃，能和各位 蒟苣 dalao 生活在同一个时代真是了不起。写页面向来无视浏览器兼容性，有各种写出失败且不可调试代码的丰富经历。轻微强迫症患者，重度 ACG 病患。
author: zthxxx
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://legacy-blog.zthxxx.me
root: /
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - '_posts/**/embed_page/**'

# Writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: headerlink
    permalinkSymbol: ''
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0 # default pages count of show
pagination_dir: page
##  pages show count details setting
index_generator:
  per_page: 5

archive_generator:
  per_page: infinity
  yearly: true
  monthly: true

tag_generator:
  per_page: 10


# Extensions
## Plugins: https://hexo.io/plugins/
### JsonContent
jsonContent:
  meta: false
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    keywords: false

  ignore:
    - baidu_verify_56LAPIAq3C.html
    - googlec3e349397eabe514.html
    - 404.html
  
### Creat sitemap
sitemap:
  path: sitemap.xml

### Adds nofollow attribute to all external links in your hexo blog posts automatically.
nofollow:
  enable: true
  exclude:
    - zthxxx.me
    - legacy-blog.zthxxx.me

## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:zthxxx/archived-legacy-blog.git
  branch: gh-pages
